### ISSUE TITLE
one key interrupts another?

### ISSUE THREAD

**Issue by zoldaten** [ollipal/sshkeyboard#12]
hi !
thanks for a lib it works on raspberry from windows ssh like a charm.

but when i use something like this:
```
if k == 'up': #forward
    mov.Forward(speed)       
if k == 'down': #backward
       mov.Backward(speed)        
if k == 'left':
        setServoAngle(servo, 140)        
if k == 'right':
        setServoAngle(servo, 90)
```
and press 'right' (or 'left') it interrupts key 'up'(or 'down') even though i still keep pressing it.
how to resolve that ?

**Comment by ollipal** [comment]
Hi! Sadly this is a limitation with this library, and [mentioned in README](https://github.com/ollipal/sshkeyboard#how-it-works). The key press detection method cannot read multiple keys at the same time. I would recommend pynput as an alternative, but it is a bit tricky to use through SSH.

**Comment by zoldaten** [comment]
i used to. pynput only works from linux like pc:
